services:
  app_proxy:
    environment:
      APP_HOST: bnussbau-trmnl-byos-laravel_app_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  app:
    image: ghcr.io/usetrmnl/byos_laravel:0.36.1@sha256:8b311aed87ce7814bb1176f74b8ef1a37d5467df8309f4837e2b65f1d5d79a09
    environment:
      - PHP_OPCACHE_ENABLE=1
      - TRMNL_PROXY_REFRESH_MINUTES=15
      - DB_DATABASE=database/storage/database.sqlite
    volumes:
      - ${APP_DATA_DIR}/data/database/:/var/www/html/database/storage
      - ${APP_DATA_DIR}/data/images/:/var/www/html/storage/app/public/images/generated
      - ${APP_DATA_DIR}/data/firmwares/:/var/www/html/storage/app/public/firmwares
    restart: on-failure