services:
  app_proxy:
    environment:
      APP_HOST: bnussbau-trmnl-byos-laravel_app_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  app:
    image: ghcr.io/usetrmnl/byos_laravel:0.28.0@sha256:7dc361d97dec7e3cb2eb6a42a9c8c47998aa761454d4b71ef04f3f60a423b691
    environment:
      - PHP_OPCACHE_ENABLE=1
      - TRMNL_PROXY_REFRESH_MINUTES=15
      - DB_DATABASE=database/storage/database.sqlite
    volumes:
      - ${APP_DATA_DIR}/data/database/:/var/www/html/database/storage
      - ${APP_DATA_DIR}/data/images/:/var/www/html/storage/app/public/images/generated
      - ${APP_DATA_DIR}/data/firmwares/:/var/www/html/storage/app/public/firmwares
    restart: on-failure